name: Build Windows Executable with uv

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Program version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Build with PyInstaller using uv
      run: |
        uv run pyinstaller --name iijwLauncher --windowed --onefile --icon=.\resources\icons\icon.ico --add-data ".\resources\icons;resources\icons" --add-data ".\resources\fonts;resources\fonts" main.py

    - name: Create and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a v${{ inputs.version }} -m "Release v${{ inputs.version }}"
        git push origin v${{ inputs.version }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ inputs.version }}
        files: dist/iijwLauncher.exe
        draft: false
        generate_release_notes: true
